# MongoDB
%dev.quarkus.mongodb.connection-string=mongodb://localhost:27017
#%dev.quarkus.mongodb.connection-string=${MONGO_PROD_URL}
%dev.quarkus.mongodb.database=habittracker
#quarkus.mongodb.dns-srv-hostname=cluster0.fhmwjts.mongodb.net

%prod.quarkus.mongodb.connection-string=${MONGO_PROD_URL}
%prod.quarkus.mongodb.database=${MONGO_PROD_DB}
#quarkus.mongodb.connection-string=mongodb+srv://rakotonirinacharlesandrea_db_user:76zgqAXmjSP1Gu4j@cluster0.fhmwjts.mongodb.net/habittracker?appName=Cluster0
#quarkus.mongodb.database=habittracker

# REST
quarkus.http.port=8080

# ========================================
# API DOCUMENTATION
# ========================================
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.path=/openapi

# ========================================
# CORS Configuration
# ========================================


quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization,Accept
quarkus.http.cors.exposed-headers=Content-Type,Authorization
#quarkus.http.cors.access-control-allow-credentials=true


mp.jwt.verify.issuer=https://acme.org/issuer
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

# Durée de validité du token
smallrye.jwt.new-token.lifespan=86400