# -------------------------------------------------------------
# Étape 1 : La compilation (Build stage)
# -------------------------------------------------------------
FROM maven:3.9.6-eclipse-temurin-21 AS build

# Définir le dossier de travail dans le conteneur de build
WORKDIR /code

# Copier le fichier de configuration Maven (pom.xml)
COPY pom.xml /code/

# Télécharger les dépendances (permet de mettre en cache cette étape si le pom change pas)
RUN mvn dependency:go-offline -B

# Copier le code source du projet
COPY src /code/src

# Compiler l'application Quarkus (génère le fameux dossier target/quarkus-app)
RUN mvn package -DskipTests

# -------------------------------------------------------------
# Étape 2 : L'image finale de production (Run stage)
# -------------------------------------------------------------
FROM registry.access.redhat.com/ubi8/openjdk-21-runtime:1.10

ENV LANGUAGE='en_US:en'

# On recrée le dossier de déploiement
WORKDIR /deployments

# IMPORTANT : On copie les fichiers depuis l'étape précédente "build"
COPY --from=build --chown=185 /code/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /code/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /code/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /code/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]